### ISSUE TITLE
Why use a Stock when there are API's which can do a lot better 

### ISSUE THREAD

**Issue by hrishikeshp7** [kritika-pattalam/practice-projects#1]

**Comment by hrishikeshp7** [comment]
Its for Quote Generator

**Comment by kritika-pattalam** [comment]
Stock? Do you mean the array?. This repo is just to practice different concepts, and that was focussed on array and other js concepts. This repo also consists a quote generator with an API https://github.com/kritika-pattalam/practice-projects/tree/main/random-chuck-norris-facts
